services:
  proof-server:
    image: "bricktowers/proof-server:6.1.0-alpha.6"
    container_name: "proof-server_$TESTCONTAINERS_UID"
    ports:
      - "6300"

  indexer:
    image: "midnightntwrk/indexer-standalone:3.0.0-alpha.19"
    container_name: 'indexer_$TESTCONTAINERS_UID'
    ports:
      - '8088'
    environment:
      RUST_LOG: "indexer=info,chain_indexer=info,indexer_api=info,wallet_indexer=info,indexer_common=info,fastrace_opentelemetry=info,info"
      # Random 32-byte hex-encoded secret used to make the standalone indexer run.
      # Only needed to satisfy the config schema â€“ not meant for secure use.
      APP__INFRA__SECRET: "303132333435363738393031323334353637383930313233343536373839303132"
      APP__INFRA__NODE__URL: "ws://node:9944"
    depends_on:
      node:
        condition: service_started
  node:
    image: 'ghcr.io/midnight-ntwrk/midnight-node:0.18.0-rc.10'
    container_name: 'node_$TESTCONTAINERS_UID'
    ports:
      - "9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      CFG_PRESET: "dev"
      SIDECHAIN_BLOCK_BENEFICIARY: '04bcf7ad3be7a5c790460be82a713af570f22e0f801f6659ab8e84a52be6969e'
